"""table changes

Revision ID: 0d44aebe258e
Revises: 47f7bf681b1d
Create Date: 2023-11-18 16:53:44.180633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d44aebe258e'
down_revision = '47f7bf681b1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie_cast_member', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cast_member_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'cast_member', ['cast_member_id'], ['castMemberID'])
        batch_op.drop_column('genre_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie_cast_member', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genre_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'cast_member', ['genre_id'], ['castMemberID'])
        batch_op.drop_column('cast_member_id')

    # ### end Alembic commands ###
