"""empty message

Revision ID: 6b04fcfe4a3e
Revises: 0d44aebe258e
Create Date: 2023-11-24 18:36:08.415947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b04fcfe4a3e'
down_revision = '0d44aebe258e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=125), nullable=True))

    with op.batch_alter_table('user_like', schema=None) as batch_op:
        batch_op.drop_column('test')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_like', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test', sa.INTEGER(), nullable=True))

    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_column('title')

    # ### end Alembic commands ###
