# file for compiling more movie lists if i can find them
# this file ignores 
import scraper
movie_titles_a = [
    "The 400 Blows",
    "La haine",
    "The Godfather",
    "The Godfather Part II",
    "Man Bites Dog",
    "The Departed",
    "Umberto D.",
    "White Heat",
    "Eddie Murphy: Raw",
    "All Quiet on the Western Front",
    "Duck Soup",
    "Mafioso",
    "Stalag 17",
    "The Shawshank Redemption",
    "The Dark Knight",
    "Fight Club",
    "Batman Begins",
    "The Big Lebowski",
    "Snatch",
    "The Good, the Bad and the Ugly",
    "Gladiator",
    "Saving Private Ryan",
    "Amélie",
    "American History X",
    "In Bruges",
    "Crash (I)",
    "Big Fish",
    "Seven Samurai",
    "Layer Cake",
    "Coming to America",
    "O Brother, Where Art Thou?",
    "Friday",
    "Donnie Brasco",
    "Raging Bull",
    "Ed Wood",
    "Primal Fear",
    "Half Baked",
    "Field of Dreams",
    "Analyze This",
    "Mean Streets",
    "The Dirty Dozen",
    "The Longest Day",
    "Combat de boxe",
    "The Errand Boy",
    "The Bellboy",
    "Six Shooter",
    "CKY2K",
    "The Dark Hours",
    "Edmond",
    "Let Him Have It",
    "Johnny Mad Dog",
    "The Public Enemy",
    "American Splendor",
    "The Football Factory",
    "The Taking of Pelham One Two Three",
    "Small Time Crooks",
    "The Business",
    "Belly",
    "Rango",
    "Transformers",
    "Limitless (I)",
    "Pulp Fiction",
    "Star Trek",
    "The Town",
    "300",
    "Heat",
    "Schindler's List",
    "The Matrix",
    "GoodFellas",
    "The Usual Suspects",
    "Up",
    "Ferris Bueller's Day Off",
    "Ip Man",
    "Mean Girls",
    "American Pie",
    "Casino Royale",
    "Back to the Future",
    "Pan's Labyrinth",
    "Dumb and Dumber",
    "Braveheart",
    "Moon",
    "Lock, Stock and Two Smoking Barrels",
    "Old School",
    "Trainspotting",
    "Slumdog Millionaire",
    "Casablanca",
    "Catch Me If You Can",
    "The Bourne Identity",
    "The Boondock Saints",
    "Blow",
    "The Fast and the Furious: Tokyo Drift",
    "Blood Diamond",
    "The Game",
    "Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb",
    "Four Lions",
    "3:10 to Yuma",
    "The Bourne Supremacy",
    "Ghostbusters",
    "Groundhog Day",
    "Wet Hot American Summer",
]
movie_titles_b = [
    "The Shawshank Redemption",
    "The Godfather",
    "The Dark Knight",
    "Pulp Fiction",
    "Schindler's List",
    "Forrest Gump",
    "Fight Club",
    "Inception",
    "The Matrix",
    "The Silence of the Lambs",
    "The Lord of the Rings: The Return of the King",
    "The Godfather: Part II",
    "The Usual Suspects",
    "Se7en",
    "The Departed",
    "Gladiator",
    "The Green Mile",
    "The Pianist",
    "The Social Network",
    "Titanic",
    "Braveheart",
    "The Terminator",
    "Back to the Future",
    "The Lion King",
    "Casablanca",
    "Gone with the Wind",
    "Citizen Kane",
    "Lawrence of Arabia",
    "The Wizard of Oz",
    "Psycho",
    "One Flew Over the Cuckoo's Nest",
    "Goodfellas",
    "Raiders of the Lost Ark",
    "Star Wars: Episode IV - A New Hope",
    "The Avengers",
    "Inglourious Basterds",
    "Django Unchained",
    "The Revenant",
    "The Great Gatsby",
    "The Grand Budapest Hotel",
    "La La Land",
    "The Shape of Water",
    "Birdman",
    "The Wolf of Wall Street",
    "Interstellar",
    "The Martian",
    "Gravity",
    "Avatar",
    "Black Panther",
    "The Dark Knight Rises",
    "Dunkirk",
    "Jurassic Park",
    "E.T. the Extra-Terrestrial",
    "The Breakfast Club",
    "The Shining",
    "A Clockwork Orange",
    "The Big Lebowski",
    "No Country for Old Men",
    "Fargo",
    "The Hateful Eight",
    "The Graduate",
    "Apocalypse Now",
    "Blade Runner",
    "2001: A Space Odyssey",
    "The Fifth Element",
    "The Matrix Reloaded",
    "The Matrix Revolutions",
    "A Beautiful Mind",
    "American Beauty",
    "The Hurt Locker",
    "No Country for Old Men",
    "12 Years a Slave",
    "Moonlight",
    "The Shape of Water",
    "Green Book",
    "Parasite",
    "Joker",
    "The Irishman",
    "Once Upon a Time in Hollywood",
    "1917",
    "Nomadland",
    "Memento",
    "Eternal Sunshine of the Spotless Mind",
    "The Prestige",
    "Donnie Darko",
    "The Truman Show",
    "Shutter Island",
    "The Sixth Sense",
    "Fight Club",
    "The Social Network"
]
movie_list = list(set((movie_titles_a+movie_titles_b)))
for movie in movie_list:
    scraper.add_movie(movie)