# file for compiling more movie lists if i can find them
# this file ignores 
import scraper
movie_titles_a = [
    "The 400 Blows",
    "La haine",
    "The Godfather",
    "The Godfather Part II",
    "Man Bites Dog",
    "The Departed",
    "Umberto D.",
    "White Heat",
    "Eddie Murphy: Raw",
    "All Quiet on the Western Front",
    "Duck Soup",
    "Mafioso",
    "Stalag 17",
    "The Shawshank Redemption",
    "The Dark Knight",
    "Fight Club",
    "Batman Begins",
    "The Big Lebowski",
    "Snatch",
    "The Good, the Bad and the Ugly",
    "Gladiator",
    "Saving Private Ryan",
    "Amélie",
    "American History X",
    "In Bruges",
    "Crash (I)",
    "Big Fish",
    "Seven Samurai",
    "Layer Cake",
    "Coming to America",
    "O Brother, Where Art Thou?",
    "Friday",
    "Donnie Brasco",
    "Raging Bull",
    "Ed Wood",
    "Primal Fear",
    "Half Baked",
    "Field of Dreams",
    "Analyze This",
    "Mean Streets",
    "The Dirty Dozen",
    "The Longest Day",
    "Combat de boxe",
    "The Errand Boy",
    "The Bellboy",
    "Six Shooter",
    "CKY2K",
    "The Dark Hours",
    "Edmond",
    "Let Him Have It",
    "Johnny Mad Dog",
    "The Public Enemy",
    "American Splendor",
    "The Football Factory",
    "The Taking of Pelham One Two Three",
    "Small Time Crooks",
    "The Business",
    "Belly",
    "Rango",
    "Transformers",
    "Limitless (I)",
    "Pulp Fiction",
    "Star Trek",
    "The Town",
    "300",
    "Heat",
    "Schindler's List",
    "The Matrix",
    "GoodFellas",
    "The Usual Suspects",
    "Up",
    "Ferris Bueller's Day Off",
    "Ip Man",
    "Mean Girls",
    "American Pie",
    "Casino Royale",
    "Back to the Future",
    "Pan's Labyrinth",
    "Dumb and Dumber",
    "Braveheart",
    "Moon",
    "Lock, Stock and Two Smoking Barrels",
    "Old School",
    "Trainspotting",
    "Slumdog Millionaire",
    "Casablanca",
    "Catch Me If You Can",
    "The Bourne Identity",
    "The Boondock Saints",
    "Blow",
    "The Fast and the Furious: Tokyo Drift",
    "Blood Diamond",
    "The Game",
    "Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb",
    "Four Lions",
    "3:10 to Yuma",
    "The Bourne Supremacy",
    "Ghostbusters",
    "Groundhog Day",
    "Wet Hot American Summer",
]
movie_titles_b = [
    "The Shawshank Redemption",
    "The Godfather",
    "The Dark Knight",
    "Pulp Fiction",
    "Schindler's List",
    "Forrest Gump",
    "Fight Club",
    "Inception",
    "The Matrix",
    "The Silence of the Lambs",
    "The Lord of the Rings: The Return of the King",
    "The Godfather: Part II",
    "The Usual Suspects",
    "Se7en",
    "The Departed",
    "Gladiator",
    "The Green Mile",
    "The Pianist",
    "The Social Network",
    "Titanic",
    "Braveheart",
    "The Terminator",
    "Back to the Future",
    "The Lion King",
    "Casablanca",
    "Gone with the Wind",
    "Citizen Kane",
    "Lawrence of Arabia",
    "The Wizard of Oz",
    "Psycho",
    "One Flew Over the Cuckoo's Nest",
    "Goodfellas",
    "Raiders of the Lost Ark",
    "Star Wars: Episode IV - A New Hope",
    "The Avengers",
    "Inglourious Basterds",
    "Django Unchained",
    "The Revenant",
    "The Great Gatsby",
    "The Grand Budapest Hotel",
    "La La Land",
    "The Shape of Water",
    "Birdman",
    "The Wolf of Wall Street",
    "Interstellar",
    "The Martian",
    "Gravity",
    "Avatar",
    "Black Panther",
    "The Dark Knight Rises",
    "Dunkirk",
    "Jurassic Park",
    "E.T. the Extra-Terrestrial",
    "The Breakfast Club",
    "The Shining",
    "A Clockwork Orange",
    "The Big Lebowski",
    "No Country for Old Men",
    "Fargo",
    "The Hateful Eight",
    "The Graduate",
    "Apocalypse Now",
    "Blade Runner",
    "2001: A Space Odyssey",
    "The Fifth Element",
    "The Matrix Reloaded",
    "The Matrix Revolutions",
    "A Beautiful Mind",
    "American Beauty",
    "The Hurt Locker",
    "No Country for Old Men",
    "12 Years a Slave",
    "Moonlight",
    "The Shape of Water",
    "Green Book",
    "Parasite",
    "Joker",
    "The Irishman",
    "Once Upon a Time in Hollywood",
    "1917",
    "Nomadland",
    "Memento",
    "Eternal Sunshine of the Spotless Mind",
    "The Prestige",
    "Donnie Darko",
    "The Truman Show",
    "Shutter Island",
    "The Sixth Sense",
    "Fight Club",
    "The Social Network"
]
horror_movies = [
    "Psycho",
    "Psycho II",
    "Psycho III",
    "Psycho IV: The Beginning",
    "The Shining",
    "Doctor Sleep",
    "Halloween",
    "Halloween II",
    "Halloween III: Season of the Witch",
    "Halloween 4: The Return of Michael Myers",
    "Halloween 5: The Revenge of Michael Myers",
    "Halloween: The Curse of Michael Myers",
    "Halloween H20: 20 Years Later",
    "Halloween: Resurrection",
    "The Exorcist",
    "Exorcist II: The Heretic",
    "Exorcist III",
    "Exorcist: The Beginning",
    "Nightmare on Elm Street",
    "A Nightmare on Elm Street 2: Freddy's Revenge",
    "A Nightmare on Elm Street 3: Dream Warriors",
    "A Nightmare on Elm Street 4: The Dream Master",
    "A Nightmare on Elm Street 5: The Dream Child",
    "Freddy's Dead: The Final Nightmare",
    "New Nightmare",
    "Texas Chainsaw Massacre",
    "Texas Chainsaw Massacre 2",
    "Leatherface: Texas Chainsaw Massacre III",
    "Texas Chainsaw Massacre: The Next Generation",
    "The Silence of the Lambs",
    "Hannibal",
    "Red Dragon",
    "Hannibal Rising",
    "Get Out",
    "Us",
    "Rosemary's Baby",
    "The Conjuring",
    "The Conjuring 2",
    "The Conjuring: The Devil Made Me Do It",
    "Hereditary",
    "Midsommar",
    "It",
    "It Chapter Two",
    "The Babadook",
    "Candyman",
    "Candyman: Farewell to the Flesh",
    "Candyman: Day of the Dead",
    "Don't Breathe",
    "Paranormal Activity",
    "Paranormal Activity 2",
    "Paranormal Activity 3",
    "Paranormal Activity 4",
    "Paranormal Activity: The Marked Ones",
    "Paranormal Activity: The Ghost Dimension",
    "The Ring",
    "The Ring Two",
    "Sinister",
    "Sinister 2",
    "Insidious",
    "Insidious: Chapter 2",
    "Insidious: Chapter 3",
    "Insidious: The Last Key",
    "Saw",
    "Saw II",
    "Saw III",
    "Saw IV",
    "Saw V",
    "Saw VI",
    "Saw 3D: The Final Chapter",
    "The Witch",
    "The Lighthouse",
    "A Nightmare on Elm Street",
    "A Nightmare on Elm Street 2: Freddy's Revenge",
    "A Nightmare on Elm Street 3: Dream Warriors",
    "A Nightmare on Elm Street 4: The Dream Master",
    "A Nightmare on Elm Street 5: The Dream Child",
    "Freddy's Dead: The Final Nightmare",
    "New Nightmare",
    "The Sixth Sense",
    "The Blair Witch Project",
    "Book of Shadows: Blair Witch 2",
    "Let the Right One In",
    "Let Me In",
    "A Tale of Two Sisters",
    "The Uninvited",
    "The Others",
    "The Others",
    "The Grudge",
    "The Grudge 2",
    "The Grudge 3",
    "Dark Water",
    "Dark Water",
    "The Birds",
    "The Wicker Man",
    "Invasion of the Body Snatchers",
    "Body Snatchers",
    "The Thing",
    "The Thing",
    "The Mist",
    "The Others",
    "The Witch",
    "Get Out",
    "A Quiet Place",
    "A Quiet Place Part II",
    "Annihilation",
    "The Cabin in the Woods",
    "Cabin Fever",
    "Don't Breathe",
    "It",
    "It Chapter Two",
    "The Conjuring",
    "The Conjuring 2",
    "The Nun",
    "Annabelle",
    "Annabelle: Creation",
    "Annabelle Comes Home",
    "Us",
    "The Ritual",
    "Doctor Sleep",
    "Oculus",
    "Oculus: Chapter 3 – The Man with the Plan",
    "The Grudge",
    "The Grudge 2",
    "The Grudge 3",
    "Sin City",
    "Sin City: A Dame to Kill For",
    "Dark Water",
    "Dark Water",
    "The Birds",
    "The Birds II: Land's End",
    "The Wicker Man",
    "The Wicker Tree",
    "Invasion of the Body Snatchers",
    "Body Snatchers",
    "The Thing",
    "The Thing",
    "The Mist",
    "The Others",
    "The Others",
    "The Witch",
    "The Witch: Part 1 – The Subversion",
    "Get Out",
    "A Quiet Place",
    "A Quiet Place Part II",
    "Annihilation",
    "Annihilation",
    "The Cabin in the Woods",
    "Cabin Fever",
    "Cabin Fever 2: Spring Fever",
    "Don't Breathe",
    "It",
    "It Chapter Two",
    "The Conjuring",
    "The Conjuring 2",
    "The Conjuring: The Devil Made Me Do It",
    "Annabelle",
    "Annabelle: Creation",
    "Annabelle Comes Home",
    "Us",
    "The Ritual",
    "Doctor Sleep",
    "Oculus",
    "Oculus: Chapter 3 – The Man with the Plan",
    "The Grudge",
    "The Grudge 2",
    "The Grudge 3",
    "Sin City",
    "Sin City: A Dame to Kill For",
    "Dark Water",
    "Dark Water",
    "The Birds",
    "The Birds II: Land's End",
    "The Wicker Man",
    "The Wicker Tree",
    "Invasion of the Body Snatchers",
    "Body Snatchers",
    "The Thing",
    "The Thing",
    "The Mist",
    "The Others",
    "The Others",
    "The Witch",
    "The Witch: Part 1 – The Subversion",
    "Get Out",
    "A Quiet Place",
    "A Quiet Place Part II",
    "Annihilation",
    "Annihilation",
    "The Cabin in the Woods",
    "Cabin Fever",
    "Cabin Fever 2: Spring Fever",
    "Don't Breathe",
    "It",
    "It Chapter Two",
    "The Conjuring",
    "The Conjuring 2",
    "The Conjuring: The Devil Made Me Do It",
    "Annabelle",
    "Annabelle: Creation",
    "Annabelle Comes Home",
    "Us",
    "The Ritual",
    "Doctor Sleep",
    "Oculus",
    "Oculus: Chapter 3 – The Man with the Plan",
    "The Grudge",
    "The Grudge 2",
    "The Grudge 3",
    "Sin City",
    "Sin City: A Dame to Kill For",
    "Dark Water",
    "Dark Water",
    "The Birds",
    "The Birds II: Land's End",
    "The Wicker Man",
    "The Wicker Tree",
    "Invasion of the Body Snatchers",
    "Body Snatchers",
    "The Thing",
    "The Thing",
    "The Mist",
    "The Others",
    "The Others",
    "The Witch",
    "The Witch: Part 1 – The Subversion",
    "Get Out",
    "A Quiet Place",
    "A Quiet Place Part II",
    "Annihilation",
    "Annihilation",
    "The Cabin in the Woods",
    "Cabin Fever",
    "Cabin Fever 2: Spring Fever",
    "Don't Breathe",
    "It",
    "It Chapter Two",
    "The Conjuring",
    "The Conjuring 2",
    "The Conjuring: The Devil Made Me Do It",
    "Annabelle",
    "Annabelle: Creation",
    "Annabelle Comes Home",
    "Us",
    "The Ritual",
    "Doctor Sleep",
    "Oculus",
    "Oculus: Chapter 3 – The Man with the Plan",
    "The Grudge",
    "The Grudge 2",
    "The Grudge 3",
    "Sin City",
    "Sin City: A Dame to Kill For",
    "Dark Water",
    "Dark Water",
    "The Birds",
    "The Birds II: Land's End",
    "The Wicker Man",
    "The Wicker Tree",
    "Invasion of the Body Snatchers",
    "Body Snatchers",
    "The Thing",
    "The Thing",
    "The Mist",
    "The Others",
    "The Others",
    "The Witch",
    "The Witch: Part 1 – The Subversion",
    "Get Out",
    "A Quiet Place",
    "A Quiet Place Part II",
    "Annihilation",
    "Annihilation",
    "The Cabin in the Woods",
    "Cabin Fever",
    "Cabin Fever 2: Spring Fever",
    "Don't Breathe",
    "It",
    "It Chapter Two",
    "The Conjuring",
    "The Conjuring 2",
    "The Conjuring: The Devil Made Me Do It",
    "Annabelle",
    "Annabelle: Creation",
    "Annabelle Comes Home",
    "Us",
    "The Ritual",
    "Doctor Sleep",
    "Oculus",
    "Oculus: Chapter 3 – The Man with the Plan",
    "The Grudge",
    "The Grudge 2",
    "The Grudge 3",
    "Sin City",
    "Sin City: A Dame to Kill For",
    "Dark Water",
    "Dark Water",
    "The Birds",
    "The Birds II: Land's End",
    "The Wicker Man",
    "The Wicker Tree",
    "Invasion of the Body Snatchers",
    "Body Snatchers",
    "The Thing",
    "The Thing",
    "The Mist",
    "The Others",
    "The Others",
    "The Witch",
    "The Witch: Part 1 – The Subversion",
    "Get Out",
    "A Quiet Place",
    "A Quiet Place Part II",
    "Annihilation",
    "Annihilation",
    "The Cabin in the Woods",
    "Cabin Fever",
    "Cabin Fever 2: Spring Fever",
    "Don't Breathe",
    "It",
    "It Chapter Two",
    "The Conjuring",
    "The Conjuring 2",
    "The Conjuring: The Devil Made Me Do It",
    "Annabelle",
    "Annabelle: Creation",
    "Annabelle Comes Home",
    "Us",
    "The Ritual",
    "Doctor Sleep",
    "Oculus",
    "Oculus: Chapter 3 – The Man with the Plan",
    "The Grudge",
    "The Grudge 2",
    "The Grudge 3",
    "Sin City",
    "Sin City: A Dame to Kill For",
    "Dark Water",
    "Dark Water",
    "The Birds",
    "The Birds II: Land's End",
    "The Wicker Man",
    "The Wicker Tree",
    "Invasion of the Body Snatchers",
    "Body Snatchers",
    "The Thing",
    "The Thing",
    "The Mist",
    "The Others",
    "The Others",
    "The Witch",
    "The Witch: Part 1 – The Subversion",
]
movie_list = list(set(horror_movies))
for movie in movie_list:
    scraper.add_movie(movie)
    print("Adding",movie)