"""nullable

Revision ID: 21033397187b
Revises: 8002dcb74790
Create Date: 2023-10-21 14:03:48.635491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21033397187b'
down_revision = '8002dcb74790'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('goal', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_goal_name'), ['name'], unique=False)

    with op.batch_alter_table('expenditure', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
        batch_op.alter_column('amount',
               existing_type=sa.FLOAT(),
               nullable=False)

    with op.batch_alter_table('income', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
        batch_op.alter_column('amount',
               existing_type=sa.FLOAT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('income', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)

    with op.batch_alter_table('expenditure', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)

    with op.batch_alter_table('goal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_goal_name'))

    op.drop_table('goal')
    # ### end Alembic commands ###
