"""init

Revision ID: b07b84f3d56e
Revises: 
Create Date: 2023-10-20 20:10:00.756857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b07b84f3d56e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expenditure',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('expenditure', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_expenditure_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenditure', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expenditure_name'))

    op.drop_table('expenditure')
    # ### end Alembic commands ###
